### ISSUE TITLE
Search by zaaknummer

### ISSUE THREAD

**Issue by joepio** [coherenza/gebouwenpaspoort-webui#15]
Customer wants to be able to search by zaaknummer (`zk-nummer`). We've added this to the `searchableAttributes`, but it does not work. This is probably because Meilisearch does not support searching in nested objects, at least not with this configuration. 

Two solutions:

- Change the `searchableAttributes` and use dot-notation ([mentioned](https://roadmap.meilisearch.com/c/105-support-nested-objects-notation) in the feature requests). 
- Move `zk-nummer` to root object

**Comment by joepio** [comment]
Nico tried setting `zaakgegevens.zk-nummer` locally, but that did not seem to work.

**Comment by joepio** [comment]
So Meilisearch [flattens nested structures](https://www.meilisearch.com/docs/learn/engine/datatypes#objects), which should mean that we can search in it using the above method. I'm not sure what is going on.

**Comment by nverwer** [comment]
There are other fields in the `searchableAttributes` that are not actually searchable. I have not investigated all of them, but here are some results:
```
      "naam", // toplevel
      "id", // toplevel
      "jaar", // nested, not searchable
      "_geo", // toplevel, composed, searchable
      "geo-EPSG28992", // nested, composed, not searchable
      "bag-aob-id", // nested, searchable
      "bag-aob-gebruiksdoel", // nested, array-valued, not searchable
      "bag-aob-oppervlakte",
      "bag-num-id", // nested, not searchable (?)
      "bag-num-id-neven",
      "bag-num-postcode", // nested, searchable (nested inside hoofdadres)
      "bag-num-postcode-neven",
      "bag-num-volledig", // nested, searchable (nested inside hoofdadres)
      "bag-num-volledig-neven",
      "bag-opr-id", // nested, searchable (nested inside hoofdadres)
      "bag-opr-id-neven",
      "bag-opr-naam",
      "bag-opr-naam-neven",
      "bag-opr-volledig",
      "bag-pnd-geo",
      "bag-pnd-geo-EPSG28992", // nested in array/object, not searchable
      "bag-pnd-id", // nested in array/object, not searchable
      "bag-pnd-oorspronkelijk-bouwjaar", // nested in array/object, not searchable
      "bag-wpl-id",
      "bag-wpl-id-neven",
      "bag-wpl-naam",
      "bag-wpl-naam-neven",
      "bwk-wijknaam",
      "bwk-subwijknaam",
      "bwk-buurtnaam",
      "bwk-subbuurtnaam",
      "zk-nummer", // nested in array/object, not searchable
      "locatie-aanduiding"
```
The non-searchable fields seem to have in common that they are inside an array or contain an array.

**Comment by nverwer** [comment]
There are other fields in the `searchableAttributes` that are not actually searchable. I checked this on the basis of a JSON record that was inserted into the Meili index.
I have not investigated all fields, but here are some results:
```
      "naam", // toplevel
      "id", // toplevel
      "jaar", // nested, not searchable
      "_geo", // toplevel, composed, searchable
      "geo-EPSG28992", // nested, composed, not searchable
      "bag-aob-id", // nested, searchable
      "bag-aob-gebruiksdoel", // nested, array-valued, not searchable
      "bag-aob-oppervlakte",
      "bag-num-id", // nested, not searchable (?)
      "bag-num-id-neven",
      "bag-num-postcode", // nested, searchable (nested inside hoofdadres)
      "bag-num-postcode-neven",
      "bag-num-volledig", // nested, searchable (nested inside hoofdadres)
      "bag-num-volledig-neven",
      "bag-opr-id", // nested, searchable (nested inside hoofdadres)
      "bag-opr-id-neven",
      "bag-opr-naam",
      "bag-opr-naam-neven",
      "bag-opr-volledig",
      "bag-pnd-geo",
      "bag-pnd-geo-EPSG28992", // nested in array/object, not searchable
      "bag-pnd-id", // nested in array/object, not searchable
      "bag-pnd-oorspronkelijk-bouwjaar", // nested in array/object, not searchable
      "bag-wpl-id",
      "bag-wpl-id-neven",
      "bag-wpl-naam",
      "bag-wpl-naam-neven",
      "bwk-wijknaam",
      "bwk-subwijknaam",
      "bwk-buurtnaam",
      "bwk-subbuurtnaam",
      "zk-nummer", // nested in array/object, not searchable
      "locatie-aanduiding"
```
The non-searchable fields seem to have in common that they are inside an array or contain an array.

**Comment by joepio** [comment]
I tried searching in nested arrays and objects (see "nestedtest" index on [blue](https://blue.pandata.nl/)), which seems to work fine. So meilisearch does allow searching in nested fields, but we still need to set `searchableAttributes` in the correct way.

**Comment by joepio** [comment]
Just ran this test:


```ts

export async function importDemo() {
  const altIndex = client.index("nestedtest");
  altIndex.addDocuments([
    {
      id: "testedoc",
      title: "TestDoc 1.",
      arr: ["alpha"],
      nested: {
        title: "bravo",
        arr: ["charlie"],
      },
    },
  ]);
  await altIndex.updateSearchableAttributes(["nested.title", "nested.arr"]);
}
```

And I can find both `charlie` and `bravo` values.  This tells me that the `updateSearchableAttributes` syntax works as I thought: you can use the dot syntax.

@nverwer So it surprises me that settings `zaakgegevens.zk-nummer` as a searchableAttribute does not work.

**Comment by nverwer** [comment]
Conclusion: It is not clear what is wrong, and MeiliSearch does not provide an overview of the content of its indexes.
Maybe we should switch to Solr, which is a much better search engine?

**Comment by joepio** [comment]
<img width="1210" alt="Screenshot 2024-11-01 at 12 49 44" src="https://github.com/user-attachments/assets/9d9e2863-dd08-4079-9fb0-cef55778a813">

**Comment by joepio** [comment]
Just ran another test, this time with an exact clone of a JSON object from GPB. Again, it seems to work just fine:

<img width="1210" alt="Screenshot 2024-11-01 at 12 49 44" src="https://github.com/user-attachments/assets/9d9e2863-dd08-4079-9fb0-cef55778a813">

Very odd.

**Comment by nverwer** [comment]
It is nice to test with a little test data, but it is irrelevant for the problem that we had.
Anyway, by removing some filterable (!) properties, the searchable properties work again.

On the 'green' server, meili does not startup any more. It would be helpful if Meilisearch had a log file, like a real search engine, but it doesn't.

**Comment by joepio** [comment]
>  It would be helpful if Meilisearch had a log file, like a real search engine, but it doesn't.

It outputs logs. I think you're running on docker, right? `docker logs meilisearch` should list logs

**Comment by joepio** [comment]
@nverwer I checked green, it's runnign the wrong meilisearch version:

```
2024-11-01T12:36:14.589235Z ERROR meilisearch: error=Your database version (1.10.2) is incompatible with your current engine version (1.11.0).
To migrate data between Meilisearch versions, please follow our guide on https://www.meilisearch.com/docs/learn/update_and_migration/updating.
Error: Your database version (1.10.2) is incompatible with your current engine version (1.11.0).
```

**Comment by nverwer** [comment]
Meili works again, and search for zaaknummer works.

**Comment by joepio** [comment]
<img width="644" alt="Screenshot 2024-11-01 at 14 34 51" src="https://github.com/user-attachments/assets/494515f5-eace-42df-998e-83f8a75df6a5">


Can confirm! Awesome @nverwer  :D
