### ISSUE TITLE
Dubbele adressen in het GBP

### ISSUE THREAD

**Issue by Joost-vandijk** [coherenza/gebouwenpaspoort-webui#16]
Het komt voor dat er in het GBP adressen dubbel staan. Dit zorgt voor verwarring bij de gebruiker, en men weet zo niet de data compleet is.

Voorbeeld: Amsterdamsestraatweg 283

Lijkt me goed om een analyse te doen welke adressen er dubbel in staan, en te onderzoeken welke redenen er achter liggen, zodat we deze kunnen verhelpen als de fout aan onze kant zit, of de gemeente kunnen adviseren als het al fout gaat in de bron.

**Comment by importalis** [comment]
Het Gebouwenpaspoort bevat de gegevens uit de BAG (Basisregistratie Adressen en Gebouwen). Dit is een authentieke bron. Dit adres komt gewoon meerdere keren voor en is geen fout.  Dit is bekend bij de gemeente, omdat we hierover al eerder vragen hebben gesteld (aan Arno). Er zijn nog meer voorbeelden van adressen die vaker voorkomen, zoals Maliebaan 31.

**Comment by Joost-vandijk** [comment]
Helder, dank. Ik koppel het terug.
