### ISSUE TITLE
Zoeken op (delen van een) zaaknummer werkt niet altijd

### ISSUE THREAD

**Issue by Joost-vandijk** [coherenza/gebouwenpaspoort-webui#17]
Bij het intypen van een zaaknummer, bijvoorbeeld HZ_WABO-23-23909, zie je halverwege andere resultaten dan als je hem compleet hebt ingetypt. In dit voorbeeld is blijft Marco Pololaan 329 ook als resultaat staan, terwijl deze ongerelateerd lijkt te zijn.

**Comment by importalis** [comment]
De gebruikte zoektechnologie houdt rekening met kleine tikfouten. Dat is handig bij het zoeken naar bijv. straatnamen, maar minder handig bij het zoeken naar een code, zoals een zaaknummer. Om dit op te lossen kunnen eindgebruikers de knop "Exact" gebruiken, die alleen de exacte matches laat zien.

**Comment by Joost-vandijk** [comment]
Makes sense, dank voor de uitleg. Ik zorg voor terugkoppeling.
